# Generated by Django 3.1.2 on 2020-11-24 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_posts'),
    ]

    operations = [
        migrations.AddField(
            model_name='posts',
            name='name',
            field=models.CharField(default=0, max_length=50),
            preserve_default=False,
        ),
    ]
